package modele;

public enum Etat {
	CREER, MODIFIER, ANNULER, DECONNECTER, SUPPRIMER, VALIDER, ECURIE, CLASSEMENT, EQUIPES, JOUEURS, CALENDRIER, TOURNOIS, RECHERCHER, JEU, PROFIL, POULE1, POULE2, POULE3, POULE4, POULEF, PHOTO, EQUIPE
}
